-- Himnos para el Hogar y la Iglesia (colección 2024-preview)
-- 72 himnos nuevos: números 1001-1062 y 1201-1210
-- Idempotente: ON CONFLICT actualiza el título
-- Ejecutar en Supabase SQL Editor

INSERT INTO "Hymn" (number, titlees, titleen)
VALUES
  (1001, 'Fuente de mis bendiciones', NULL),
  (1002, 'Cuando vuelva el Salvador', NULL),
  (1003, 'Reina paz en mi ser', NULL),
  (1004, 'Andaré con Cristo', NULL),
  (1005, '¿Cómo sentirme triste?', NULL),
  (1006, 'En tu corazón', NULL),
  (1007, 'En Ti pensamos partiendo el pan', NULL),
  (1008, 'Agua viva, pan de vida', NULL),
  (1009, 'Getsemaní', NULL),
  (1010, '¡Sublime gracia del Señor', NULL),
  (1011, 'Somos niños y entonamos la canción', NULL),
  (1012, 'Puedo orar cada día al Padre', NULL),
  (1013, 'Cada día Dios me da Su gracia', NULL),
  (1014, 'Mi buen pastor es Jehová', NULL),
  (1015, 'Oh, cuán pleno, cuán profundo', NULL),
  (1016, 'Mirad las marcas de Jesús', NULL),
  (1017, 'El Cristo es', NULL),
  (1018, 'Ven, oh, Cristo, al pesebre', NULL),
  (1019, 'Amar igual que Tú', NULL),
  (1020, 'Tiernamente Jesús hoy nos llama', NULL),
  (1021, 'Cristo me ama, lo sé', NULL),
  (1022, 'Con fe en cada paso', NULL),
  (1023, 'Firme en las promesas de Jesús, el Rey', NULL),
  (1024, 'Tengo fe en Jesús, mi Señor', NULL),
  (1025, 'Que mi alma siempre esté', NULL),
  (1026, 'Lugares santos', NULL),
  (1027, 'Soy bienvenido a Su hogar', NULL),
  (1028, 'Mi pequeña luz', NULL),
  (1029, 'Los dones que el Padre derrama', NULL),
  (1030, 'Dios siempre cerca está', NULL),
  (1031, 'Venid, oíd la voz de Cristo', NULL),
  (1032, 'Mirad a Cristo', NULL),
  (1033, 'Placentero nos es trabajar', NULL),
  (1034, 'Soy pionero también', NULL),
  (1035, 'Honraré Su día', NULL),
  (1036, 'El bien yo quiero elegir', NULL),
  (1037, 'Vivir, servir, orar y cantar', NULL),
  (1038, 'Es Jehová mi buen pastor', NULL),
  (1039, 'Es gracias al Señor', NULL),
  (1040, 'Prevalece Su voz', NULL),
  (1041, 'Por mí la vida diste Tú', NULL),
  (1042, 'Clemente Dios, hoy cual ayer', NULL),
  (1043, 'Oh, Redentor, rogamos Tu perdón', NULL),
  (1044, 'Así nos ministró Cristo', NULL),
  (1045, '"Oh, ven a Mí", pidió Jesús', NULL),
  (1046, 'Puedes tú contar los astros', NULL),
  (1047, 'Dios me conoce', NULL),
  (1048, 'Oh, Padre Eterno, a Ti oramos', NULL),
  (1049, 'José oró con fe', NULL),
  (1050, 'Ven a mí', NULL),
  (1051, 'Señor, un buen día es hoy', NULL),
  (1052, '¡Oh, qué gozo nos da!', NULL),
  (1053, 'Mis convenios', NULL),
  (1054, 'Al bautizarme a Cristo seguiré', NULL),
  (1055, 'El poder del Santo Espíritu', NULL),
  (1056, 'Elías y la suave voz', NULL),
  (1057, 'Mi pastor es Cristo; Su oveja soy', NULL),
  (1058, 'Mi canto en la noche, Jesús, mi Señor', NULL),
  (1059, 'El mundo es de Dios', NULL),
  (1060, 'Un arca construiré', NULL),
  (1061, 'Cuán dulce hogar de amor', NULL),
  (1062, 'Nuestro ayuno, oh, Señor', NULL),
  (1201, 'El Señor resucitó, ¡aleluya!', NULL),
  (1202, 'El divino Jesús nació', NULL),
  (1203, '¿Qué niño es este que, al dormir', NULL),
  (1204, 'Estrella de luz', NULL),
  (1205, 'Oh, santos, ¡glorias dad!', NULL),
  (1206, '¿Viste tú cuando mi Señor murió?', NULL),
  (1207, 'Paz, paz, paz', NULL),
  (1208, '¡Ve! Dilo en las montañas', NULL),
  (1209, 'Pequeñito en pesebre', NULL),
  (1210, 'Tiempo atrás, en un jardín', NULL)
ON CONFLICT (number) DO UPDATE SET
  titlees = EXCLUDED.titlees;