// AUTO-GENERATED by scripts/hymns-fetch.ts — DO NOT EDIT BY HAND.
// Re-run with: tsx scripts/hymns-fetch.ts
// Source: https://www.churchofjesuschrist.org/study/manual/hymns?lang=spa
// Generated at: 2026-06-11T01:01:38.001Z
// Total entries: 281 (209 himnario tradicional + 72 Para el Hogar y la Iglesia)

export interface HymnSeed {
  number: number;
  titleEs: string;
  titleEn?: string;
}

export const HYMNS: HymnSeed[] = [
  {
    "number": 1,
    "titleEs": "Ya rompe el alba"
  },
  {
    "number": 2,
    "titleEs": "El Espíritu de Dios"
  },
  {
    "number": 3,
    "titleEs": "Ya regocijemos"
  },
  {
    "number": 4,
    "titleEs": "Bandera de Sión"
  },
  {
    "number": 5,
    "titleEs": "Oh Dios de Israel"
  },
  {
    "number": 6,
    "titleEs": "Israel, Jesús os llama"
  },
  {
    "number": 7,
    "titleEs": "Id, vosotros mensajeros"
  },
  {
    "number": 8,
    "titleEs": "¿Qué es lo que vieron en las alturas?"
  },
  {
    "number": 9,
    "titleEs": "Un ángel del Señor"
  },
  {
    "number": 10,
    "titleEs": "Te damos, Señor, nuestras gracias"
  },
  {
    "number": 11,
    "titleEs": "Dios manda a profetas"
  },
  {
    "number": 12,
    "titleEs": "Pedimos hoy por ti"
  },
  {
    "number": 13,
    "titleEs": "Bendice, Dios, a nuestro Profeta"
  },
  {
    "number": 14,
    "titleEs": "La oración del Profeta"
  },
  {
    "number": 15,
    "titleEs": "Loor al Profeta"
  },
  {
    "number": 16,
    "titleEs": "Un pobre forastero"
  },
  {
    "number": 17,
    "titleEs": "¡Oh, está todo bien!"
  },
  {
    "number": 18,
    "titleEs": "Oh Sión, santuario de libertad"
  },
  {
    "number": 19,
    "titleEs": "Por Tus dones loor cantamos"
  },
  {
    "number": 20,
    "titleEs": "Gozoso día llega ya"
  },
  {
    "number": 21,
    "titleEs": "¡Salve, Sión! Es tu día ilustre"
  },
  {
    "number": 22,
    "titleEs": "En las cumbres de los montes"
  },
  {
    "number": 23,
    "titleEs": "Bella Sión"
  },
  {
    "number": 24,
    "titleEs": "El alba ya rompe"
  },
  {
    "number": 25,
    "titleEs": "Jehová aparece en Su gloria"
  },
  {
    "number": 26,
    "titleEs": "Hijos del Señor, venid"
  },
  {
    "number": 27,
    "titleEs": "Oh Rey de reyes, ven"
  },
  {
    "number": 28,
    "titleEs": "Himno de batalla de la República"
  },
  {
    "number": 29,
    "titleEs": "Ven, oh día prometido"
  },
  {
    "number": 30,
    "titleEs": "A Cristo Rey Jesús"
  },
  {
    "number": 31,
    "titleEs": "Oh, creaciones del Señor"
  },
  {
    "number": 32,
    "titleEs": "Baluarte firme es nuestro Dios"
  },
  {
    "number": 33,
    "titleEs": "Honor, loor y gloria"
  },
  {
    "number": 34,
    "titleEs": "Oh, Santo Dios, omnipotente ser"
  },
  {
    "number": 35,
    "titleEs": "Haznos pensar en Ti, Señor"
  },
  {
    "number": 36,
    "titleEs": "Padre bendito, venimos a Ti"
  },
  {
    "number": 37,
    "titleEs": "Glorias cantad a Dios"
  },
  {
    "number": 38,
    "titleEs": "Santos, avanzad"
  },
  {
    "number": 39,
    "titleEs": "Jehová, sé nuestro guía"
  },
  {
    "number": 40,
    "titleEs": "Qué firmes cimientos"
  },
  {
    "number": 41,
    "titleEs": "¡Grande eres Tú!"
  },
  {
    "number": 42,
    "titleEs": "Jesús es mi luz"
  },
  {
    "number": 43,
    "titleEs": "Por la belleza terrenal"
  },
  {
    "number": 44,
    "titleEs": "El sublime Creador"
  },
  {
    "number": 45,
    "titleEs": "Oración de gratitud"
  },
  {
    "number": 46,
    "titleEs": "Elevemos nuestros himnos"
  },
  {
    "number": 47,
    "titleEs": "Caros niños, Dios os ama"
  },
  {
    "number": 48,
    "titleEs": "Divina Luz"
  },
  {
    "number": 49,
    "titleEs": "Señor, te necesito"
  },
  {
    "number": 50,
    "titleEs": "Más cerca, Dios, de ti"
  },
  {
    "number": 51,
    "titleEs": "Guíame, oh Salvador"
  },
  {
    "number": 52,
    "titleEs": "Guíame a Ti"
  },
  {
    "number": 53,
    "titleEs": "¡Oh Jesús, mi gran amor!"
  },
  {
    "number": 54,
    "titleEs": "Paz, cálmense"
  },
  {
    "number": 55,
    "titleEs": "Dios da valor"
  },
  {
    "number": 56,
    "titleEs": "Jehová mi Pastor es"
  },
  {
    "number": 57,
    "titleEs": "El amor del Salvador"
  },
  {
    "number": 58,
    "titleEs": "Roca de eternidad"
  },
  {
    "number": 59,
    "titleEs": "Mirad al Salvador"
  },
  {
    "number": 60,
    "titleEs": "Venid a Cristo"
  },
  {
    "number": 61,
    "titleEs": "Venid a Mí"
  },
  {
    "number": 62,
    "titleEs": "No desmayéis, oh santos"
  },
  {
    "number": 63,
    "titleEs": "Aunque colmados de pesar"
  },
  {
    "number": 64,
    "titleEs": "Venid, los que a Dios amáis"
  },
  {
    "number": 65,
    "titleEs": "¿Sin contestar?"
  },
  {
    "number": 66,
    "titleEs": "Cuán dulce la ley de Dios"
  },
  {
    "number": 67,
    "titleEs": "Si la vía es penosa"
  },
  {
    "number": 68,
    "titleEs": "La fe"
  },
  {
    "number": 69,
    "titleEs": "¿Dónde hallo el solaz?"
  },
  {
    "number": 70,
    "titleEs": "Sé humilde"
  },
  {
    "number": 71,
    "titleEs": "Más santidad dame"
  },
  {
    "number": 72,
    "titleEs": "Creo en Cristo"
  },
  {
    "number": 73,
    "titleEs": "Yo sé que vive mi Señor"
  },
  {
    "number": 74,
    "titleEs": "Vive mi Señor"
  },
  {
    "number": 75,
    "titleEs": "Testimonio"
  },
  {
    "number": 76,
    "titleEs": "Tan sólo con pensar en Ti"
  },
  {
    "number": 77,
    "titleEs": "Deja que el Espíritu te enseñe"
  },
  {
    "number": 78,
    "titleEs": "Oh dulce, grata oración"
  },
  {
    "number": 79,
    "titleEs": "La oración del alma es"
  },
  {
    "number": 80,
    "titleEs": "Secreta oración"
  },
  {
    "number": 81,
    "titleEs": "¿Pensaste orar?"
  },
  {
    "number": 82,
    "titleEs": "Padre en los cielos"
  },
  {
    "number": 83,
    "titleEs": "Entonad sagrado son"
  },
  {
    "number": 84,
    "titleEs": "Dulce Tu obra es, Señor"
  },
  {
    "number": 85,
    "titleEs": "El día santo del Señor"
  },
  {
    "number": 86,
    "titleEs": "Nuestro bondadoso Padre"
  },
  {
    "number": 87,
    "titleEs": "Cual rocío, que destila"
  },
  {
    "number": 88,
    "titleEs": "Placentero nos es trabajar"
  },
  {
    "number": 89,
    "titleEs": "Para siempre Dios esté con Vos"
  },
  {
    "number": 90,
    "titleEs": "Padre, antes de partir"
  },
  {
    "number": 91,
    "titleEs": "Al partir cantemos"
  },
  {
    "number": 92,
    "titleEs": "Hemos sentido Tu amor"
  },
  {
    "number": 93,
    "titleEs": "A Ti, Señor"
  },
  {
    "number": 94,
    "titleEs": "Ya termina el día"
  },
  {
    "number": 95,
    "titleEs": "El fuego del Espíritu"
  },
  {
    "number": 96,
    "titleEs": "El ocaso viene ya"
  },
  {
    "number": 97,
    "titleEs": "Ante Ti, Señor, Tu grey"
  },
  {
    "number": 98,
    "titleEs": "Conmigo quédate, Señor"
  },
  {
    "number": 99,
    "titleEs": "Acompáñame"
  },
  {
    "number": 100,
    "titleEs": "Dios, bendícenos"
  },
  {
    "number": 101,
    "titleEs": "Dios, escúchanos orar"
  },
  {
    "number": 102,
    "titleEs": "Hoy con humildad te pido"
  },
  {
    "number": 103,
    "titleEs": "La Santa Cena"
  },
  {
    "number": 104,
    "titleEs": "Oh Dios, Eterno Padre"
  },
  {
    "number": 105,
    "titleEs": "Jesús de Nazaret"
  },
  {
    "number": 106,
    "titleEs": "Cuán grato es cantar loor"
  },
  {
    "number": 107,
    "titleEs": "Pedimos Tu Espíritu"
  },
  {
    "number": 108,
    "titleEs": "Mansos, reverentes hoy"
  },
  {
    "number": 109,
    "titleEs": "Cantemos todos a Jesús"
  },
  {
    "number": 110,
    "titleEs": "En memoria de Tu muerte"
  },
  {
    "number": 111,
    "titleEs": "En el Calvario, en la cruz"
  },
  {
    "number": 112,
    "titleEs": "El Padre tanto nos amó"
  },
  {
    "number": 113,
    "titleEs": "Ya nos juntamos otra vez"
  },
  {
    "number": 114,
    "titleEs": "Cristo, el Redentor, murió"
  },
  {
    "number": 115,
    "titleEs": "Nos reunimos, Padre, hoy"
  },
  {
    "number": 116,
    "titleEs": "Jesús, en la corte celestial"
  },
  {
    "number": 117,
    "titleEs": "¡Murió! El Redentor murió"
  },
  {
    "number": 118,
    "titleEs": "Asombro me da"
  },
  {
    "number": 119,
    "titleEs": "En un lejano cerro fue"
  },
  {
    "number": 120,
    "titleEs": "Tan humilde al nacer"
  },
  {
    "number": 121,
    "titleEs": "Himno de la Pascua de Resurrección"
  },
  {
    "number": 122,
    "titleEs": "Cristo ha resucitado"
  },
  {
    "number": 123,
    "titleEs": "¡Regocijad! Jesús nació"
  },
  {
    "number": 124,
    "titleEs": "Venid, adoremos"
  },
  {
    "number": 125,
    "titleEs": "Jesús en pesebre"
  },
  {
    "number": 126,
    "titleEs": "Cantan santos ángeles"
  },
  {
    "number": 127,
    "titleEs": "Noche de luz"
  },
  {
    "number": 128,
    "titleEs": "A medianoche se oyó"
  },
  {
    "number": 129,
    "titleEs": "Oh, pueblecito de Belén"
  },
  {
    "number": 130,
    "titleEs": "Escuchad el son triunfal"
  },
  {
    "number": 131,
    "titleEs": "Asombro dio a los magos"
  },
  {
    "number": 132,
    "titleEs": "La primera Navidad"
  },
  {
    "number": 133,
    "titleEs": "Campanas de Navidad"
  },
  {
    "number": 134,
    "titleEs": "En la Judea, en tierra de Dios"
  },
  {
    "number": 135,
    "titleEs": "Hoy sembramos la semilla"
  },
  {
    "number": 136,
    "titleEs": "Todos los santos"
  },
  {
    "number": 137,
    "titleEs": "Tú me has dado muchas bendiciones, Dios"
  },
  {
    "number": 138,
    "titleEs": "Señor, yo te seguiré"
  },
  {
    "number": 139,
    "titleEs": "Ama el Pastor las ovejas"
  },
  {
    "number": 140,
    "titleEs": "A Dios el Padre y a Jesús"
  },
  {
    "number": 141,
    "titleEs": "¿En el mundo he hecho bien?"
  },
  {
    "number": 142,
    "titleEs": "Otro año ha pasado"
  },
  {
    "number": 143,
    "titleEs": "A Dios ofrecemos gozosa canción"
  },
  {
    "number": 144,
    "titleEs": "A la gloria marcharemos"
  },
  {
    "number": 145,
    "titleEs": "La voz, ya, del eterno"
  },
  {
    "number": 146,
    "titleEs": "Tengo gozo en mi alma hoy"
  },
  {
    "number": 147,
    "titleEs": "Recojamos los destellos"
  },
  {
    "number": 148,
    "titleEs": "Si hay gozo en tu corazón"
  },
  {
    "number": 149,
    "titleEs": "Trabajad con fervor"
  },
  {
    "number": 150,
    "titleEs": "Siembra gozo"
  },
  {
    "number": 151,
    "titleEs": "Oh, hablemos con tiernos acentos"
  },
  {
    "number": 152,
    "titleEs": "No hablemos con enojo"
  },
  {
    "number": 153,
    "titleEs": "Oíd el toque del clarín"
  },
  {
    "number": 154,
    "titleEs": "Haz tú lo justo"
  },
  {
    "number": 155,
    "titleEs": "Haz el bien"
  },
  {
    "number": 156,
    "titleEs": "Señor del cielo, Jehová"
  },
  {
    "number": 157,
    "titleEs": "Cuenta tus bendiciones"
  },
  {
    "number": 158,
    "titleEs": "Trabajemos hoy en la obra"
  },
  {
    "number": 159,
    "titleEs": "Con valor marchemos"
  },
  {
    "number": 160,
    "titleEs": "Tu casa amamos, Dios"
  },
  {
    "number": 161,
    "titleEs": "Llamados a servir"
  },
  {
    "number": 162,
    "titleEs": "Somos los soldados"
  },
  {
    "number": 163,
    "titleEs": "¡Mirad! Reales huestes"
  },
  {
    "number": 164,
    "titleEs": "Pon tu hombro a la lid"
  },
  {
    "number": 165,
    "titleEs": "Tu palabra"
  },
  {
    "number": 166,
    "titleEs": "Firmes creced en la fe"
  },
  {
    "number": 167,
    "titleEs": "A vencer"
  },
  {
    "number": 168,
    "titleEs": "Juventud de Israel"
  },
  {
    "number": 169,
    "titleEs": "Al mundo ve a predicar"
  },
  {
    "number": 170,
    "titleEs": "¿Quién sigue al Señor?"
  },
  {
    "number": 171,
    "titleEs": "La luz de la verdad"
  },
  {
    "number": 172,
    "titleEs": "Cuando enseñe a Tus hijos"
  },
  {
    "number": 173,
    "titleEs": "El fin se acerca"
  },
  {
    "number": 174,
    "titleEs": "Qué maravillosas Tus obras"
  },
  {
    "number": 175,
    "titleEs": "A donde me mandes iré"
  },
  {
    "number": 176,
    "titleEs": "Palabras de amor"
  },
  {
    "number": 177,
    "titleEs": "¿Qué es la verdad?"
  },
  {
    "number": 178,
    "titleEs": "Nuestra mente se refleja"
  },
  {
    "number": 179,
    "titleEs": "La barra de hierro"
  },
  {
    "number": 180,
    "titleEs": "Al leer las Escrituras"
  },
  {
    "number": 181,
    "titleEs": "Cuando raya el nuevo dia"
  },
  {
    "number": 182,
    "titleEs": "Bienvenido, día santo"
  },
  {
    "number": 183,
    "titleEs": "Santos templos de Sión"
  },
  {
    "number": 184,
    "titleEs": "Id, oh santos, a los templos"
  },
  {
    "number": 185,
    "titleEs": "En los postreros días"
  },
  {
    "number": 186,
    "titleEs": "Volved vuestro corazón"
  },
  {
    "number": 187,
    "titleEs": "Oh mi Padre"
  },
  {
    "number": 188,
    "titleEs": "Quienes nos brindan su amor"
  },
  {
    "number": 189,
    "titleEs": "Oh Padre, llénanos de amor"
  },
  {
    "number": 190,
    "titleEs": "Hay un hogar eterno"
  },
  {
    "number": 191,
    "titleEs": "Con maravillas obra Dios"
  },
  {
    "number": 192,
    "titleEs": "¿Por qué somos?"
  },
  {
    "number": 193,
    "titleEs": "El hogar es como el cielo"
  },
  {
    "number": 194,
    "titleEs": "Cuando hay amor"
  },
  {
    "number": 195,
    "titleEs": "Las familias pueden ser eternas"
  },
  {
    "number": 196,
    "titleEs": "Soy un hijo de Dios"
  },
  {
    "number": 197,
    "titleEs": "Siempre obedece los mandamientos"
  },
  {
    "number": 198,
    "titleEs": "Hazme andar en la luz"
  },
  {
    "number": 199,
    "titleEs": "Dios vive"
  },
  {
    "number": 200,
    "titleEs": "La luz de Dios"
  },
  {
    "number": 201,
    "titleEs": "Dios cuida a sus hijos"
  },
  {
    "number": 202,
    "titleEs": "En el pueblo de Sión"
  },
  {
    "number": 203,
    "titleEs": "Amad a otros"
  },
  {
    "number": 204,
    "titleEs": "Hijos de nuestro Padre"
  },
  {
    "number": 205,
    "titleEs": "Sirvamos unidas (Mujeres)"
  },
  {
    "number": 206,
    "titleEs": "Venid, los que tenéis de Dios el sacerdocio (Hombres)"
  },
  {
    "number": 207,
    "titleEs": "Oh vos que sois llamados (Hombres)"
  },
  {
    "number": 208,
    "titleEs": "Brillan rayos de clemencia (Hombres)"
  },
  {
    "number": 209,
    "titleEs": "Oh élderes de Israel (Hombres)"
  },
  {
    "number": 1001,
    "titleEs": "Fuente de mis bendiciones"
  },
  {
    "number": 1002,
    "titleEs": "Cuando vuelva el Salvador"
  },
  {
    "number": 1003,
    "titleEs": "Reina paz en mi ser"
  },
  {
    "number": 1004,
    "titleEs": "Andaré con Cristo"
  },
  {
    "number": 1005,
    "titleEs": "¿Cómo sentirme triste?"
  },
  {
    "number": 1006,
    "titleEs": "En tu corazón"
  },
  {
    "number": 1007,
    "titleEs": "En Ti pensamos partiendo el pan"
  },
  {
    "number": 1008,
    "titleEs": "Agua viva, pan de vida"
  },
  {
    "number": 1009,
    "titleEs": "Getsemaní"
  },
  {
    "number": 1010,
    "titleEs": "¡Sublime gracia del Señor"
  },
  {
    "number": 1011,
    "titleEs": "Somos niños y entonamos la canción"
  },
  {
    "number": 1012,
    "titleEs": "Puedo orar cada día al Padre"
  },
  {
    "number": 1013,
    "titleEs": "Cada día Dios me da Su gracia"
  },
  {
    "number": 1014,
    "titleEs": "Mi buen pastor es Jehová"
  },
  {
    "number": 1015,
    "titleEs": "Oh, cuán pleno, cuán profundo"
  },
  {
    "number": 1016,
    "titleEs": "Mirad las marcas de Jesús"
  },
  {
    "number": 1017,
    "titleEs": "El Cristo es"
  },
  {
    "number": 1018,
    "titleEs": "Ven, oh, Cristo, al pesebre"
  },
  {
    "number": 1019,
    "titleEs": "Amar igual que Tú"
  },
  {
    "number": 1020,
    "titleEs": "Tiernamente Jesús hoy nos llama"
  },
  {
    "number": 1021,
    "titleEs": "Cristo me ama, lo sé"
  },
  {
    "number": 1022,
    "titleEs": "Con fe en cada paso"
  },
  {
    "number": 1023,
    "titleEs": "Firme en las promesas de Jesús, el Rey"
  },
  {
    "number": 1024,
    "titleEs": "Tengo fe en Jesús, mi Señor"
  },
  {
    "number": 1025,
    "titleEs": "Que mi alma siempre esté"
  },
  {
    "number": 1026,
    "titleEs": "Lugares santos"
  },
  {
    "number": 1027,
    "titleEs": "Soy bienvenido a Su hogar"
  },
  {
    "number": 1028,
    "titleEs": "Mi pequeña luz"
  },
  {
    "number": 1029,
    "titleEs": "Los dones que el Padre derrama"
  },
  {
    "number": 1030,
    "titleEs": "Dios siempre cerca está"
  },
  {
    "number": 1031,
    "titleEs": "Venid, oíd la voz de Cristo"
  },
  {
    "number": 1032,
    "titleEs": "Mirad a Cristo"
  },
  {
    "number": 1033,
    "titleEs": "Placentero nos es trabajar"
  },
  {
    "number": 1034,
    "titleEs": "Soy pionero también"
  },
  {
    "number": 1035,
    "titleEs": "Honraré Su día"
  },
  {
    "number": 1036,
    "titleEs": "El bien yo quiero elegir"
  },
  {
    "number": 1037,
    "titleEs": "Vivir, servir, orar y cantar"
  },
  {
    "number": 1038,
    "titleEs": "Es Jehová mi buen pastor"
  },
  {
    "number": 1039,
    "titleEs": "Es gracias al Señor"
  },
  {
    "number": 1040,
    "titleEs": "Prevalece Su voz"
  },
  {
    "number": 1041,
    "titleEs": "Por mí la vida diste Tú"
  },
  {
    "number": 1042,
    "titleEs": "Clemente Dios, hoy cual ayer"
  },
  {
    "number": 1043,
    "titleEs": "Oh, Redentor, rogamos Tu perdón"
  },
  {
    "number": 1044,
    "titleEs": "Así nos ministró Cristo"
  },
  {
    "number": 1045,
    "titleEs": "\"Oh, ven a Mí\", pidió Jesús"
  },
  {
    "number": 1046,
    "titleEs": "Puedes tú contar los astros"
  },
  {
    "number": 1047,
    "titleEs": "Dios me conoce"
  },
  {
    "number": 1048,
    "titleEs": "Oh, Padre Eterno, a Ti oramos"
  },
  {
    "number": 1049,
    "titleEs": "José oró con fe"
  },
  {
    "number": 1050,
    "titleEs": "Ven a mí"
  },
  {
    "number": 1051,
    "titleEs": "Señor, un buen día es hoy"
  },
  {
    "number": 1052,
    "titleEs": "¡Oh, qué gozo nos da!"
  },
  {
    "number": 1053,
    "titleEs": "Mis convenios"
  },
  {
    "number": 1054,
    "titleEs": "Al bautizarme a Cristo seguiré"
  },
  {
    "number": 1055,
    "titleEs": "El poder del Santo Espíritu"
  },
  {
    "number": 1056,
    "titleEs": "Elías y la suave voz"
  },
  {
    "number": 1057,
    "titleEs": "Mi pastor es Cristo; Su oveja soy"
  },
  {
    "number": 1058,
    "titleEs": "Mi canto en la noche, Jesús, mi Señor"
  },
  {
    "number": 1059,
    "titleEs": "El mundo es de Dios"
  },
  {
    "number": 1060,
    "titleEs": "Un arca construiré"
  },
  {
    "number": 1061,
    "titleEs": "Cuán dulce hogar de amor"
  },
  {
    "number": 1062,
    "titleEs": "Nuestro ayuno, oh, Señor"
  },
  {
    "number": 1201,
    "titleEs": "El Señor resucitó, ¡aleluya!"
  },
  {
    "number": 1202,
    "titleEs": "El divino Jesús nació"
  },
  {
    "number": 1203,
    "titleEs": "¿Qué niño es este que, al dormir"
  },
  {
    "number": 1204,
    "titleEs": "Estrella de luz"
  },
  {
    "number": 1205,
    "titleEs": "Oh, santos, ¡glorias dad!"
  },
  {
    "number": 1206,
    "titleEs": "¿Viste tú cuando mi Señor murió?"
  },
  {
    "number": 1207,
    "titleEs": "Paz, paz, paz"
  },
  {
    "number": 1208,
    "titleEs": "¡Ve! Dilo en las montañas"
  },
  {
    "number": 1209,
    "titleEs": "Pequeñito en pesebre"
  },
  {
    "number": 1210,
    "titleEs": "Tiempo atrás, en un jardín"
  }
];
