/**
 * Fetch the LDS hymnal index from churchofjesuschrist.org and extract all 341
 * hymn numbers + Spanish titles. Writes the result as a TypeScript module that
 * can be imported by the seed script.
 *
 * Why not just use the static data? The spec says we should try webfetch first
 * and fall back to a hardcoded list. This script automates the webfetch path
 * so re-running it gives us a fresh dump of titles without manual copy-paste.
 */
import * as fs from "node:fs";
import * as path from "node:path";

const SOURCE_URL = "https://www.churchofjesuschrist.org/study/manual/hymns?lang=spa";
const OUT_FILE = path.resolve(process.cwd(), "db/hymns-data.ts");

interface Hymn {
  number: number;
  titleEs: string;
  titleEn?: string;
}

function extractHymns(html: string): Hymn[] {
  // The page is server-rendered React HTML. Hymn entries look like:
  //   <a class="..." href="/study/manual/hymns/the-morning-breaks?lang=spa" id="li1" ...>
  //     <div class="itemTitle-MXhtV">
  //       <p>
  //         <span class="songNumber-vZmKj">1</span>
  //         <span>Ya rompe el alba</span>
  //       </p>
  //     </div>
  //   </a>
  // Match the anchor tag with its id="liN" attribute, then pull number + title
  // from the inner <span class="songNumber...">N</span><span>title</span>.
  const re = /id="li(\d{1,3})"[\s\S]*?<span class="songNumber-[^"]+">(\d+)<\/span>\s*<span>([^<]+)<\/span>/g;
  const byNumber = new Map<number, Hymn>();
  let m: RegExpExecArray | null;
  while ((m = re.exec(html)) !== null) {
    const idNum = parseInt(m[1], 10);
    const num = parseInt(m[2], 10);
    const title = m[3].trim();
    if (num < 1 || num > 341) continue;
    // Some pages wrap the number separately; trust whichever gives us the right number
    if (idNum !== num) continue;
    if (!byNumber.has(num)) {
      byNumber.set(num, { number: num, titleEs: title });
    }
  }
  return Array.from(byNumber.values()).sort((a, b) => a.number - b.number);
}

async function main(): Promise<void> {
  console.log(`[hymns] fetching ${SOURCE_URL}`);
  const res = await fetch(SOURCE_URL, {
    headers: {
      "User-Agent": "Mozilla/5.0 (compatible; Bloomingdale2-Bootstrap/1.0)",
      "Accept-Language": "es-MX,es;q=0.9",
    },
  });
  if (!res.ok) {
    throw new Error(`HTTP ${res.status} ${res.statusText}`);
  }
  const html = await res.text();
  console.log(`[hymns] fetched ${html.length} bytes`);
  const hymns = extractHymns(html);
  console.log(`[hymns] extracted ${hymns.length} hymns`);

  if (hymns.length < 341) {
    console.warn(`[hymns] WARN: only got ${hymns.length} (expected 341). Will fall back to hardcoded titles for missing numbers.`);
  }

  // Generate TypeScript module
  const banner = `// AUTO-GENERATED by scripts/hymns-fetch.ts — DO NOT EDIT BY HAND.
// Re-run with: tsx scripts/hymns-fetch.ts
// Source: ${SOURCE_URL}
// Generated at: ${new Date().toISOString()}
// Total entries: ${hymns.length}

export interface HymnSeed {
  number: number;
  titleEs: string;
  titleEn?: string;
}

export const HYMNS: HymnSeed[] = ${JSON.stringify(hymns, null, 2)};
`;
  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, banner, "utf8");
  console.log(`[hymns] wrote ${OUT_FILE}`);
}

main().catch((err) => {
  console.error("[hymns] failed:", err);
  process.exit(1);
});
